version: '3.8'

services:
  calendar-api:
    image: ghcr.io/surmatik/ceviwet-calendar-api:latest
    ports:
      - "5000:5000"
    volumes:
      - ./credentials.json:/app/credentials.json
    environment:
      - FLASK_ENV=production
    restart: always
