version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./credentials.json:/app/credentials.json
    environment:
      - FLASK_ENV=production
    restart: always
